# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='valor',
            field=models.CharField(default='1', max_length=1),
            preserve_default=False,
        ),
    ]
